project:
  type: website

website:
  title: "My Personal Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Example Analysis"
        href: Example_analysis.qmd

